<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>LogCollector.Host</RootNamespace>
    <AssemblyName>LogCollector.Host</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LogCollector.Infrastructure\LogCollector.Infrastructure.csproj" />
  </ItemGroup>
</Project>
